quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/insurance

quarkus.hibernate-orm.database.generation=update

quarkus.hibernate-orm.log.sql=true

kafka.bootstrap.servers=localhost:9092

# Kafka Consumer - proposal-submitted-in
mp.messaging.incoming.proposal-submitted-in.connector=smallrye-kafka
mp.messaging.incoming.proposal-submitted-in.topic=policy-proposal-submitted
mp.messaging.incoming.proposal-submitted-in.value.deserializer=com.ifglife.kafka.serialization.PolicyProposalSubmittedEventDeserializer

# Kafka Producer - proposal-submitted-out
mp.messaging.outgoing.proposal-submitted-out.connector=smallrye-kafka
mp.messaging.outgoing.proposal-submitted-out.topic=policy-proposal-submitted
mp.messaging.outgoing.proposal-submitted-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Kafka Producer - proposal-processed-out
mp.messaging.outgoing.proposal-processed-out.connector=smallrye-kafka
mp.messaging.outgoing.proposal-processed-out.topic=policy-proposal-processed
mp.messaging.outgoing.proposal-processed-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer